create_db:
        conn_type = "mysql+pymysql"
        user = "root"
        password = "avc_project"
        host = "mysql-avc-app-michel.cmq30xngrjmp.us-east-2.rds.amazonaws.com"
        port = 3306
        DATABASE_NAME = 'msia423'
add_to_db:
        conn_type = "mysql+pymysql"
        user = "root"
        password = "avc_project"
        host = "mysql-avc-app-michel.cmq30xngrjmp.us-east-2.rds.amazonaws.com"
        port = 3306
        DATABASE_NAME = 'msia423'
        user_pick = "111000"
        genre = "humor"
        book_rec = "calvin and hobbes"
        book_cover = "url"

